#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"
EWW="$HOME/.bin/eww"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} open-many \
		   background \
		   profile \
		   system \
		   clock \
		   uptime \
		   music \
		   gitlab \
		   reddit \
		   twitter \
		   youtube \
		   weather \
		   apps \
		   mail \
		   logout \
		   sleep \
		   reboot \
		   poweroff \
		   folders
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
    WT=$(cat ~/.local/share/weather_token)
    sed -i "s/KEY=\"\"/KEY=\"$WT\"/" ~/dotfiles/eww/scripts/weather_info
    /home/guillaume/dotfiles/eww/scripts/weather_info --getdata
    sed -i "s/KEY=.*/KEY=\"\"/" ~/dotfiles/eww/scripts/weather_info
	run_eww
else
	${EWW} close-all
	rm "$FILE"
fi
