# https://spaceship-prompt.sh/config/intro/#Create-a-config-file

SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_COLOR=#ff5859

SPACESHIP_DIR_TRUNC_REPO=false

SPACESHIP_DIR_COLOR=magenta
SPACESHIP_GIT_BRANCH_COLOR=#5fd787

# SPACESHIP_ASYNC_SYMBOL="⏳"
SPACESHIP_ASYNC_SYMBOL=""

