#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.xyz"
EWW="$HOME/.bin/eww"

run_or_focus() {
  exist=$(wmctrl -l |grep -v grep |grep $1|wc -l)
  if [[ "$exist" == 0 ]]; then
    $1 &
  else
    wmctrl -a $1
  fi
}

if [[ "$1" == "--ff" ]]; then
	${EWW} close-all && rm -rf "$FILE" && run_or_focus qutebrowser

elif [[ "$1" == "--tg" ]]; then
	${EWW} close-all && rm -rf "$FILE" && run_or_focus telegram-desktop

elif [[ "$1" == "--dc" ]]; then
	${EWW} close-all && rm -rf "$FILE" && run_or_focus -a discord

elif [[ "$1" == "--tr" ]]; then
	${EWW} close-all && rm -rf "$FILE" && kitty &

elif [[ "$1" == "--fm" ]]; then
	${EWW} close-all && rm -rf "$FILE" && thunar ~ &

elif [[ "$1" == "--te" ]]; then
	${EWW} close-all && rm -rf "$FILE" && run_or_focus teams

elif [[ "$1" == "--sp" ]]; then
	${EWW} close-all && rm -rf "$FILE" && run_or_focus spotify

elif [[ "$1" == "--an" ]]; then
	${EWW} close-all && rm -rf "$FILE" && run_or_focus anki

elif [[ "$1" == "--bw" ]]; then
	${EWW} close-all && rm -rf "$FILE" && run_or_focus bitwarden-desktop

fi
